### ISSUE TITLE
New release of js_of_ocaml breaks picos.thread

### ISSUE THREAD

**Issue by hhugo** [ocaml-multicore/picos#332]
The new release of jsoo https://github.com/ocaml/opam-repository/pull/26932 breaks `picos.thread` on ocaml < 5 because it no longer exports a `caml_ml_domain_id` runtime value on ocaml < 5.
I don't rely understand why picos is build with ocaml 4.

Is it ok to apply the following patch to thread.ocaml4.js ?
```diff
//Provides: caml_thread_self
//Requires: caml_ml_domain_id, caml_failwith, caml_thread
function caml_thread_self(unit) {
-   if (caml_ml_domain_id(unit) != caml_thread[1])
-    caml_failwith('caml_thread_self: spawning of domains is not supported')
  return caml_thread
}
```

**Comment by polytypic** [comment]
> I don't rely understand why picos is build with ocaml 4.

Generally speaking Picos fully supports OCaml 4.  One can use systhreads (i.e. the `Thread` module) in OCaml 4 and then run Picos fibers on systhreads.  As long one doesn't use large numbers of fibers, it is entirely possible then to write programs than can be built and run fine with either OCaml 4 or OCaml 5.  The main intention behind this, of course, is to potentially help with porting applications to OCaml 5.

> Is it ok to apply the following patch to thread.ocaml4.js ?

Hmm... Yes... I think we should also trim the `Requires`, but otherwise I think it should be fine.

Does #333 look good to you?

**Comment by hhugo** [comment]
Your PR looks good.
